version: "3.3"

services:
  mysql:
    image: mysql:5.7
    container_name: spring_mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - spring-net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    expose:
      - 3306
  spring:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    expose:
      - "8080"
    networks:
      - spring-net
networks:
  spring-net:
    driver: bridge